version: '3.8'
services:
  frontend:
    build: ./pathfind
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27018/Register
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27016:27017"
