name: MERN CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: pathfind  
        run: npm install

      - name: Run Tests (if any)
        working-directory: pathfind  
        run: npm test || echo "No tests found"

      - name: Build Frontend
        working-directory: pathfind  
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend Docker Image
        working-directory: pathfind  
        run: |
          docker build -t yashdocker39/mern-frontend:latest .
          docker push yashdocker39/mern-frontend:latest

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: server 
        run: npm install

      - name: Run Tests (if any)
        working-directory: server  
        run: npm test || echo "No tests found"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend Docker Image
        working-directory: server  
        run: |
          docker build -t yashdocker39/mern-backend:latest .
          docker push yashdocker39/mern-backend:latest

  deploy:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull yashdocker39/mern-frontend:latest
            docker pull yashdocker39/mern-backend:latest
            docker-compose up -d --force-recreate
